import pandas as pd
import json
from wordcloud import WordCloud
import matplotlib.pyplot as plt

def word_cloud_from_json(word, year, json_df):
#saves a wordcloud as .jpg which is generated by data from json_df (lines = words, columns = years)
    try:
        frequencies = dict(json_df.loc[word, year])
    except IndexError:
        'Input dataframe not of correct structure.'
    
    wordcloud = WordCloud(max_words=100, max_font_size=60, background_color = 'white').fit_words(frequencies)
    
    fig = plt.figure(1, figsize=(12, 12))
    plt.axis("off")
    plt.imshow(wordcloud)
    output_filename = "Wordcloud_" + word + "_" + str(year) +".jpg"
    wordcloud.to_file(output_filename)

	
json_file = 'data//most_similar_by_year.json'
json_df = pd.read_json(json_file) #does not work with 'data//most_similar_by_publisher.json' yet

word_cloud_from_json('flüchtling', 2015, json_df)